name: Calculator workflow

on:
  push:
    branches: ["feature/calculator-pnini"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: server workflow
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.2"
          cache: maven
          distribution: 'temurin'
      - name: run java container with maven
        run: docker run --entrypoint bash --name java_server -v ${PWD}:/app -p 8080:8080  maven:3-openjdk-17
        working-directory: Calculator-Task/server
      - name: test server
        run: mvn test
        working-directory: Calculator-Task/server
